/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiCalendarMonth: typeof import('~icons/mdi/calendar-month')['default']
    IMdiImageAddOutline: typeof import('~icons/mdi/image-add-outline')['default']
    Live2d: typeof import('./src/components/live-2d.vue')['default']
    MainHeader: typeof import('./src/components/main-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UdeitorPlus: typeof import('./src/components/udeitor-plus.vue')['default']
  }
}
