/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMaterialSymbolsHomeRounded: typeof import('~icons/material-symbols/home-rounded')['default']
    IMdiAlarmArmHome: typeof import('~icons/mdi/alarm-arm-home')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiHomeAlarmArmHome: typeof import('~icons/mdi/home-alarm-arm-home')['default']
    IMdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    IMdiHomeOutlineRounded: typeof import('~icons/mdi/home-outline-rounded')['default']
    IMdiHomeRounded: typeof import('~icons/mdi/home-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
